all:
  children:
    control:
      hosts:
        control-node:
          ansible_host: 10.0.2.11
    
    web_servers:
      hosts:
        web-server:
          ansible_host: 10.0.2.12
    
    app_servers:
      hosts:
        app-server:
          ansible_host: 10.0.2.13
    
    db_servers:
      hosts:
        db-server:
          ansible_host: 10.0.2.14
    
    managed_nodes:
      children:
        web_servers:
        app_servers:
        db_servers:
